# Generated by Django 3.1 on 2020-10-20 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='updated_at',
        ),
    ]
