# Generated by Django 3.1 on 2020-10-20 05:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20201020_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 10, 20, 5, 57, 38, 873737, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
