# Generated by Django 3.1 on 2020-10-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_userdetails_friend_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
